=== MJozsef2000/Y86I0I_XMLGyak/XMLTaskY86I0I/XMLSchemaY86I0I.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- Egyszerű típusok -->
<xs:simpleType name="csaladi_allapot_type" final="restriction" >
    <xs:restriction base="xs:string">
        <xs:enumeration value="Házas" />
        <xs:enumeration value="Egyedülálló" />
        <xs:enumeration value="Elvált" />
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="epites_type" final="restriction" >
    <xs:restriction base="xs:string">
        <xs:enumeration value="Újépítésű Tégla" />
        <xs:enumeration value="Újépítésű Beton" />
        <xs:enumeration value="Régi Tégla" />
				<xs:enumeration value="Régi Beton" />
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="ablak_type" final="restriction" >
    <xs:restriction base="xs:string">
        <xs:enumeration value="Van" />
        <xs:enumeration value="Nincs" />
    </xs:restriction>
</xs:simpleType>
<xs:simpleType name="emelet_type" final="restriction" >
    <xs:restriction base="xs:byte">
        <xs:enumeration value="1" />
        <xs:enumeration value="2" />
				<xs:enumeration value="3" />
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="pozicio_type">
  <xs:restriction base="xs:string">
    <xs:minLength value="1"/>
    <xs:pattern value="([a-zA-Z])*"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="szolgalati_hely_type">
  <xs:restriction base="xs:string">
    <xs:minLength value="5"/>
    <xs:pattern value="([a-z\s*A-Z])*"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="nev_type">
  <xs:restriction base="xs:string">
    <xs:pattern value="[A-Z][a-zA-Z]*( [A-Z][a-zA-Z]*)*"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="iranyitoszam_type">
  <xs:restriction base="xs:string">
    <xs:length value="4"/>
    <xs:pattern value="([0-9])*"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="hazszam_type">
  <xs:restriction base="xs:string">
    <xs:maxLength value="3"/>
    <xs:pattern value="([0-9])*"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="utca_type">
  <xs:restriction base="xs:string">
    <xs:pattern value="[A-Z][a-zA-Z]*( [A-Z][a-zA-Z]*)*"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="muszak_type">
  <xs:restriction base="xs:string">
    <xs:enumeration value="Nappali"/>
    <xs:enumeration value="Delutanos"/>
    <xs:enumeration value="Esti"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="datum_type">
  <xs:restriction base="xs:string">
      <xs:pattern value="(19|20)\d\d.(0[1-9]|1[012]).(0[1-9]|[12][0-9]|3[01])"/>
  </xs:restriction>
</xs:simpleType>

  <xs:element name="MJ_Borton">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="szemelyzet">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="pozicio" type="pozicio_type" />
							<xs:element name="szolgalati_hely" type="szolgalati_hely_type" />
							<xs:element name="csaladi_allapot" type="csaladi_allapot_type" />
						</xs:sequence>
						<xs:attribute name="SZ-A" type="xs:unsignedByte" use="required" />
						<xs:attribute name="SZEM_ID" type="xs:unsignedByte" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element maxOccurs="unbounded" name="alkalmazott">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="eletkor" type="xs:unsignedByte" />
							<xs:element name="nev" type="nev_type" />
							<xs:element name="lakhely">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="iranyitoszam" type="iranyitoszam_type" />
										<xs:element name="hazszam" type="xs:unsignedByte" />
										<xs:element name="utca" type="utca_type" />
										<xs:element name="varos" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="ALK_ID" type="xs:unsignedByte" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element maxOccurs="unbounded" name="beosztas">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="muszak" type="muszak_type" />
						</xs:sequence>
						<xs:attribute name="BE-A" type="xs:unsignedByte" use="required" />
						<xs:attribute name="BE-B" type="xs:string" use="required" />
            <xs:attribute name="BE_ID" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element maxOccurs="unbounded" name="borton_epulet">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="cellak_szama" type="xs:unsignedByte" />
							<xs:element name="kapacitas" type="xs:unsignedByte" />
							<xs:element name="epulet_neve" type="xs:string" />
							<xs:element name="epites" type="epites_type" />
						</xs:sequence>
						<xs:attribute name="BOR_ID" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element maxOccurs="unbounded" name="cellak">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="cella_kapacitas" type="xs:unsignedByte" />
							<xs:element name="emelet" type="emelet_type" />
							<xs:element name="ablak" type="ablak_type" />
						</xs:sequence>
						<xs:attribute name="CEL_ID" type="xs:string" use="required" />
						<xs:attribute name="C-B" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element maxOccurs="unbounded" name="rab">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nev" type="xs:string" />
							<xs:element name="eletkor" type="xs:unsignedByte" />
							<xs:element name="letoltendo">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="kezdet" type="datum_type" />
										<xs:element name="veg" type="datum_type" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="RAB_ID" type="xs:string" use="required" />
						<xs:attribute name="R-C" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
    <!-- Elsődleges kulcsok -->
    <xs:key name="szem_id">
      <xs:selector xpath="szemelyzet" />
      <xs:field xpath="@SZEM_ID" />
    </xs:key>
    <xs:key name="alk_id">
      <xs:selector xpath="alkalmazott" />
      <xs:field xpath="@ALK_ID" />
    </xs:key>
    <xs:key name="be_id">
      <xs:selector xpath="beosztas" />
      <xs:field xpath="@BE_ID" />
    </xs:key>
    <xs:key name="bor_id">
      <xs:selector xpath="borton_epulet" />
      <xs:field xpath="@BOR_ID" />
    </xs:key>
    <xs:key name="cel_id">
      <xs:selector xpath="cellak" />
      <xs:field xpath="@CEL_ID" />
    </xs:key>
    <xs:key name="rab_id">
      <xs:selector xpath="rab" />
      <xs:field xpath="@RAB_ID" />
    </xs:key>

    <!-- Idegen kulcsok -->
    <xs:keyref refer="alk_id" name="alkalmazott_szemelyzet_idegen_kulcs">
            <xs:selector xpath="szemelyzet" />
            <xs:field xpath="@SZ-A" />
    </xs:keyref>
    <xs:keyref refer="alk_id" name="alkalmazott_idegen_kulcs">
            <xs:selector xpath="beosztas" />
            <xs:field xpath="@BE-A" />
    </xs:keyref>
    <xs:keyref refer="bor_id" name="borton_idegen_kulcs">
            <xs:selector xpath="beosztas" />
            <xs:field xpath="@BE-B" />
    </xs:keyref>
    <xs:keyref refer="bor_id" name="borton_cella_idegen_kulcs">
            <xs:selector xpath="cellak" />
            <xs:field xpath="@C-B" />
    </xs:keyref>
    <xs:keyref refer="cel_id" name="cella_rab_idegen_kulcs">
            <xs:selector xpath="rab" />
            <xs:field xpath="@R-C" />
    </xs:keyref>
	</xs:element>


</xs:schema>

=== MJozsef2000/Y86I0I_XMLGyak/XMLTaskY86I0I/DOMParseY86I0I/XMLY86I0I.xml
<?xml version="1.0" encoding="UTF-8"?>

<MJ_Borton xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="XMLSchemaY86I0I.xsd">
  <!-- Személyzet -->
  <szemelyzet SZ-A="01" SZEM_ID="100">
    <pozicio>Takarito</pozicio>
    <szolgalati_hely>Folyosok</szolgalati_hely>
  </szemelyzet>
  <szemelyzet SZ-A="02" SZEM_ID="101">
    <pozicio>Szakacs</pozicio>
    <szolgalati_hely>Konyha</szolgalati_hely>
  </szemelyzet>
  <szemelyzet SZ-A="03" SZEM_ID="102">
    <pozicio>Bortonor</pozicio>
    <szolgalati_hely>Borton epuletek</szolgalati_hely>
  </szemelyzet>
  <szemelyzet SZ-A="04" SZEM_ID="103">
    <pozicio>Sofor</pozicio>
    <szolgalati_hely>Kocsibejaro</szolgalati_hely>
  </szemelyzet>
  <szemelyzet SZ-A="05" SZEM_ID="104">
    <pozicio>Orvos</pozicio>
    <szolgalati_hely>Borton korhaz</szolgalati_hely>
  </szemelyzet>

<!-- Alkalmazottak általános adatai -->
  <alkalmazott ALK_ID = "01">
    <eletkor>34</eletkor>
    <nev>Kis Karoly</nev>
    <lakhely>
      <iranyitoszam>3529</iranyitoszam>
      <hazszam>23</hazszam>
      <utca>Afonyas</utca>
      <varos>Miskolc</varos>
    </lakhely>
  </alkalmazott>
  <alkalmazott ALK_ID = "02">
    <eletkor>55</eletkor>
    <nev>Mucsi Zoltan</nev>
    <lakhely>
      <iranyitoszam>1032</iranyitoszam>
      <hazszam>102</hazszam>
      <utca>Kossuth Lajos</utca>
      <varos>Budapest</varos>
    </lakhely>
  </alkalmazott>
  <alkalmazott ALK_ID = "03">
    <eletkor>57</eletkor>
    <nev>Miliczki Jozsef</nev>
    <lakhely>
      <iranyitoszam>3012</iranyitoszam>
      <hazszam>141</hazszam>
      <utca>Beke</utca>
      <varos>Győr</varos>
    </lakhely>
  </alkalmazott>
  <alkalmazott ALK_ID = "04">
    <eletkor>25</eletkor>
    <nev>Turing Ferenc</nev>
    <lakhely>
      <iranyitoszam>2525</iranyitoszam>
      <hazszam>26</hazszam>
      <utca>Saros</utca>
      <varos>Kecskemét</varos>
    </lakhely>
  </alkalmazott>
  <alkalmazott ALK_ID = "05">
    <eletkor>44</eletkor>
    <nev>Eros Antonia</nev>
    <lakhely>
      <iranyitoszam>4412</iranyitoszam>
      <hazszam>56</hazszam>
      <utca>Szabadsag Ter</utca>
      <varos>Szeged</varos>
    </lakhely>
  </alkalmazott>
<!-- Alkalmazottak összekapcsolása Börtön épületekkel -->
  <beosztas BE-A="01" BE-B="A" BE_ID="1">
    <muszak>Esti</muszak>
  </beosztas>
  <beosztas BE-A="01" BE-B="B" BE_ID="2">
    <muszak>Nappali</muszak>
  </beosztas>
  <beosztas BE-A="02" BE-B="C" BE_ID="3">
    <muszak>Esti</muszak>
  </beosztas>
  <beosztas BE-A="03" BE-B="C" BE_ID="4">
    <muszak>Delutanos</muszak>
  </beosztas>
  <beosztas BE-A="04" BE-B="A" BE_ID="5">
    <muszak>Nappali</muszak>
  </beosztas>
  <beosztas BE-A="04" BE-B="C" BE_ID="6">
    <muszak>Delutanos</muszak>
  </beosztas>
  <beosztas BE-A="05" BE-B="B" BE_ID="7">
    <muszak>Esti</muszak>
  </beosztas>
  <!-- Börtön épületek -->
  <borton_epulet BOR_ID = "A">
    <cellak_szama>30</cellak_szama>
    <kapacitas>120</kapacitas>
    <epulet_neve>Szecheny borton</epulet_neve>
  </borton_epulet>
  <borton_epulet BOR_ID = "B">
    <cellak_szama>45</cellak_szama>
    <kapacitas>220</kapacitas>
    <epulet_neve>Janos borton</epulet_neve>
  </borton_epulet>
  <borton_epulet BOR_ID = "C">
    <cellak_szama>50</cellak_szama>
    <kapacitas>240</kapacitas>
    <epulet_neve>Solyom borton</epulet_neve>
  </borton_epulet>
<!-- "A" börtön cellái-->
  <cellak CEL_ID = "a1" C-B="A">
    <cella_kapacitas>4</cella_kapacitas>
    <emelet>1</emelet>
  </cellak>
  <cellak CEL_ID = "a2" C-B="A">
    <cella_kapacitas>4</cella_kapacitas>
    <emelet>1</emelet>
  </cellak>
  <cellak CEL_ID = "a3" C-B="A">
    <cella_kapacitas>2</cella_kapacitas>
    <emelet>2</emelet>
  </cellak>
  <cellak CEL_ID = "a4" C-B="A">
    <cella_kapacitas>1</cella_kapacitas>
    <emelet>2</emelet>
  </cellak>
  <cellak CEL_ID = "a5" C-B="A">
    <cella_kapacitas>5</cella_kapacitas>
    <emelet>2</emelet>
  </cellak>
<!-- "B" börtön cellái-->
  <cellak CEL_ID = "b1" C-B="B">
    <cella_kapacitas>3</cella_kapacitas>
    <emelet>1</emelet>
  </cellak>
  <cellak CEL_ID = "b2" C-B="B">
    <cella_kapacitas>3</cella_kapacitas>
    <emelet>2</emelet>
  </cellak>
  <cellak CEL_ID = "b3" C-B="B">
    <cella_kapacitas>3</cella_kapacitas>
    <emelet>3</emelet>
  </cellak>
  <cellak CEL_ID = "b4" C-B="B">
    <cella_kapacitas>2</cella_kapacitas>
    <emelet>3</emelet>
  </cellak>
  <cellak CEL_ID = "b5" C-B="B">
    <cella_kapacitas>5</cella_kapacitas>
    <emelet>3</emelet>
  </cellak>

  <!-- "C" börtön cellái-->
  <cellak CEL_ID = "c1" C-B="C">
    <cella_kapacitas>4</cella_kapacitas>
    <emelet>1</emelet>
  </cellak>
  <cellak CEL_ID = "c2" C-B="C">
    <cella_kapacitas>3</cella_kapacitas>
    <emelet>1</emelet>
  </cellak>
  <cellak CEL_ID = "c3" C-B="C">
    <cella_kapacitas>3</cella_kapacitas>
    <emelet>1</emelet>
  </cellak>
  <cellak CEL_ID = "c4" C-B="C">
    <cella_kapacitas>4</cella_kapacitas>
    <emelet>2</emelet>
  </cellak>
  <cellak CEL_ID = "c5" C-B="C">
    <cella_kapacitas>2</cella_kapacitas>
    <emelet>3</emelet>
  </cellak>
  <!-- Rabok cellákra osztva -->
  <rab RAB_ID = "rab1" R-C="a1">
    <nev>Gengszter Lajos</nev>
    <eletkor>38</eletkor>
    <letoltendo>
      <kezdet>2000.10.12</kezdet>
      <veg>2010.10.12</veg>
    </letoltendo>
  </rab>
  <rab RAB_ID = "rab2" R-C="a3">
    <nev>Bűnöző Ferenc</nev>
    <eletkor>54</eletkor>
    <letoltendo>
      <kezdet>1992.03.22</kezdet>
      <veg>2003.03.22</veg>
    </letoltendo>
  </rab>
  <rab RAB_ID = "rab3" R-C="b1">
    <nev>Lopó Benedek</nev>
    <eletkor>22</eletkor>
    <letoltendo>
      <kezdet>2001.06.01</kezdet>
      <veg>2002.05.15</veg>
    </letoltendo>
  </rab>
  <rab RAB_ID = "rab4" R-C="b2">
    <nev>Hamiskártyás Ernő</nev>
    <eletkor>32</eletkor>
    <letoltendo>
      <kezdet>2010.01.01</kezdet>
      <veg>2015.01.01</veg>
    </letoltendo>
  </rab>
  <rab RAB_ID = "rab5" R-C="b2">
    <nev>Gonosz Gergő</nev>
    <eletkor>47</eletkor>
    <letoltendo>
      <kezdet>2006.04.30</kezdet>
      <veg>2010.07.15</veg>
    </letoltendo>
  </rab>
  <rab RAB_ID = "rab6" R-C="c1">
    <nev>Ártatlan Áron</nev>
    <eletkor>51</eletkor>
    <letoltendo>
      <kezdet>1995.10.12</kezdet>
      <veg>2020.01.01</veg>
    </letoltendo>
  </rab>
</MJ_Borton>
